### ISSUE TITLE
Installation ?

### ISSUE THREAD

**Issue by ahmedmaalej** [Hennrik/Coherent-Point-Drift-Python#1]
How can I install this package?
import cpd generates
ImportError: No module named cpd
Thnx

**Comment by yanbo-huang** [comment]
If you are in the root path of the package (the same directory of `examples.ipynb`), you can successfully import it.

**Comment by ahmedmaalej** [comment]
Thnkx.
I cloned the project (coherent-point-drift/....) inside my working folder I tried different solution for importing, then I copied the cpd folder inside my working folder and it worked.

**Comment by Hennrik** [comment]
It's seems this issue should be closed long time ago.
